services:
  postgres:
    image: postgres
    container_name: memovo_db
    restart: always
    env_file:
      - memovo-backend/.env
    ports:
      - 5433:5432
    volumes:
      - memovo_volume:/var/lib/postgresql/data
  node:
    container_name: node
    build: ./memovo-backend
    ports:
      - 4000:4000
    env_file:
      - memovo-backend/.env
    depends_on:
      - postgres

  react:
    container_name: react
    build: ./memovo-frontend
    volumes:
      - react-volume:/var/www/html

  nginx:
    container_name: nginx
    build: ./nginx
    ports:
      - 80:80
    volumes:
      - react-volume:/var/www/html
    depends_on:
      - db
      - node
      - react

volumes:
  memovo_volume:
  react-volume:
