services:
  db:
    image: postgres
    container_name: memovo_db
    restart: always
    env_file:
      - memovo-backend/.env
    ports:
      - 5433:5432
    volumes:
      - memovo_volume:/var/lib/postgresql/data
  node:
    container_name: node
    build: .
    ports:
      - 1234:4000
    env_file:
      - memovo-backend/.env
    depends_on:
      - db

  react:
    container_name: react
    build: ./memovo-frontend
    volumes:
      - react-volume:/var/www/html

  nginx:
    container_name: nginx
    build: ./nginx
    ports:
      - 8080:80
    volumes:
      - react-volume:/var/www/html
    depends_on:
      - db
      - node
      - react

volumes:
  memovo_volume:
  react-volume:
