services:
  db:
    image: postgres
    container_name: memovo_db
    env_file:
      - memovo-backend/.env.test
    ports:
      - 5433:5432
  node:
    container_name: node
    build: ./memovo-backend
    ports:
      - 4000:4000
    env_file:
      - memovo-backend/.env.test
    depends_on:
      - db
